# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gasworks < Formula
  desc "SSO login + getToken (EIA) CLI for Gas City"
  homepage "https://github.com/gascity/gasworks"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.0/gasworks_0.1.0_darwin_amd64.tar.gz"
      sha256 "15ff3e1ffdbd0678fc0c7f639c6493ea277b07667114ce4a5e111e21c6d89bce"

      define_method(:install) do
        bin.install "gasworks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.0/gasworks_0.1.0_darwin_arm64.tar.gz"
      sha256 "77c6dddc2471799292f6cb628dba224711879206a75402cd1bc3270afc69ee29"

      define_method(:install) do
        bin.install "gasworks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.0/gasworks_0.1.0_linux_amd64.tar.gz"
      sha256 "1b86d6cd2aec0f6ef5e10e7a05ab133933f8b62bbc84cbedc094a74bc7163e71"
      define_method(:install) do
        bin.install "gasworks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.0/gasworks_0.1.0_linux_arm64.tar.gz"
      sha256 "025a310c95c1570098425dc7263d0c8df3d293cf4e03f3bda03885d6247882b8"
      define_method(:install) do
        bin.install "gasworks"
      end
    end
  end

  test do
    system "#{bin}/gasworks", "version"
  end
end
