# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gasworks < Formula
  desc "SSO login + getToken (EIA) CLI for Gas City"
  homepage "https://github.com/gascity/gasworks"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.1/gasworks_0.1.1_darwin_amd64.tar.gz"
      sha256 "612bf7500571d7acf26b7b41468cdad6a82e6b39049fe534c6f47dd1ca04c8e4"

      define_method(:install) do
        bin.install "gasworks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.1/gasworks_0.1.1_darwin_arm64.tar.gz"
      sha256 "19da9f4cf188965abaeb3e721e788ceca058214f41399f62c9cef987a2215ca1"

      define_method(:install) do
        bin.install "gasworks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.1/gasworks_0.1.1_linux_amd64.tar.gz"
      sha256 "101506c55c8df6952c91b4788ca998075e3310fc9d32a7ea972b6c459800a0d6"
      define_method(:install) do
        bin.install "gasworks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.1/gasworks_0.1.1_linux_arm64.tar.gz"
      sha256 "1183c4027798a4713c6e81e0d98b787e5b59e89bfb990ec74ab8a6cb41b358c7"
      define_method(:install) do
        bin.install "gasworks"
      end
    end
  end

  test do
    system "#{bin}/gasworks", "version"
  end
end
