# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gasworks < Formula
  desc "SSO login + getToken (EIA) CLI for Gas City"
  homepage "https://github.com/gascity/gasworks"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.2/gasworks_0.1.2_darwin_amd64.tar.gz"
      sha256 "2ba775b01fdfbb935dabcbdb65ae58e0951f48a8d777fb6e19a77caf32443a84"

      define_method(:install) do
        bin.install "gasworks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.2/gasworks_0.1.2_darwin_arm64.tar.gz"
      sha256 "4d0dedac98945b91c83359bb018969a08ce3bc7f8c748929860de23f7fe604ee"

      define_method(:install) do
        bin.install "gasworks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.2/gasworks_0.1.2_linux_amd64.tar.gz"
      sha256 "96082ec2fa6806ee9773cd499c0e8f869b1bdf1e88ae5640d1eaa0e318264f23"
      define_method(:install) do
        bin.install "gasworks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gascity/gasworks/releases/download/v0.1.2/gasworks_0.1.2_linux_arm64.tar.gz"
      sha256 "a8747d36f5a5644e3eb3323baea8ce38f23adefa3c7df8c3ff97f8a39f018dd2"
      define_method(:install) do
        bin.install "gasworks"
      end
    end
  end

  test do
    system "#{bin}/gasworks", "version"
  end
end
